// Re-exported from consolidated types — see types/index.ts
export type {
  RecommendationPreferences,
  RecommendedMatch,
  RecommendationResult,
  RecommendationUsage,
  RecommendationPriorityFactor,
  RecommendationPriority,
  RecommendationFeatureLevel,
  RecommendationPhoneType,
  RecommendationMetrics,
  RankedPhoneRecommendation,
  RecommendationExplanation,
  RecommendationApiPriorityFactor,
  RecommendationApiRequest,
  RecommendationApiSpecifications,
  RecommendationApiItem,
  RecommendationEngineItem,
  RecommendationApiResponse,
} from "./index";
